name: hostess
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - boto3
  - cytoolz
  - dill
  - dustgoggles
  - fabric
  - fire
  - invoke
  - more-itertools
  - pandas
  - protobuf
  - psutil
  - pympler
  - python-magic
  - pyyaml
  - requests
  - rich
  - textual
