name: hostess
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - boto3
  - cytoolz
  - dustgoggles
  - fire
  - flask
  - more-itertools
  - pandas
  - pympler
  - python-magic
  - requests
  - rich
  - sh>=2.0.0




